name: CI
"on":
  pull_request: null
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Begin CI...
        uses: actions/checkout@v3
      - name: Use Node 12
        uses: actions/setup-node@v3
        with:
          node-version: lts/*
      - name: Use cached node_modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: nodeModules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            nodeModules-
      - name: Install dependencies
        run: npm ci
        env:
          CI: true
      - name: Lint
        run: npm run lint
        env:
          CI: true
      - name: Test
        run: npm test -- --coverage
        env:
          CI: true
      - name: Build
        run: npm run build
        env:
          CI: true
      - name: Codecov
        run: npx codecov
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
